//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.A_City {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtPostCode;
		protected global::System.Web.UI.WebControls.TextBox txtTelRegionCode;
		protected global::System.Web.UI.WebControls.TextBox txtTelSizeNumber;
		protected global::System.Web.UI.WebControls.TextBox txtCityLevel;
		protected global::System.Web.UI.WebControls.TextBox txtCity;
		protected global::System.Web.UI.WebControls.TextBox txtRegionId;
		protected global::System.Web.UI.WebControls.TextBox txtRegionLId;
		protected global::System.Web.UI.WebControls.TextBox txtGBCode;
		protected global::System.Web.UI.WebControls.TextBox txtProvinceId;
		protected global::System.Web.UI.WebControls.CheckBox chkStateEnable;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
