//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.A_City {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblPostCode;
	protected global::System.Web.UI.WebControls.Label lblTelRegionCode;
	protected global::System.Web.UI.WebControls.Label lblTelSizeNumber;
	protected global::System.Web.UI.WebControls.Label lblCityLevel;
	protected global::System.Web.UI.WebControls.Label lblCity;
	protected global::System.Web.UI.WebControls.Label lblRegionId;
	protected global::System.Web.UI.WebControls.Label lblRegionLId;
	protected global::System.Web.UI.WebControls.Label lblGBCode;
	protected global::System.Web.UI.WebControls.Label lblProvinceId;
	protected global::System.Web.UI.WebControls.Label lblStateEnable;


       
    }
}
