server:
  port: 9527
spring:
  application:
    name: springcloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zuul9527.com  #修改Eureka上的默认描述信息
    prefer-ip-address: true  # 为true可以显示服务的ip地址
info:
  app.name: wu-springcloud
  company.name: blog.wulei2921625957.com

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept  # 原来的id
    mydept.path: /mydept/**
  ignored-services:
    - springcloud-provider-dept  #不能再使用这个路径访问了
  prefix: /wu     # 这个是前缀  比如： http://www.wu.com:9527/wu/mydept/dept/get/1
