server:
  port: 80

#Eureka配置
eureka:
  client:
    register-with-eureka: false #不向eureka中注册自己
    # "defaultZone", "http://localhost:8761/eureka/"
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

#开启降级
feign:
  hystrix:
    enabled: true