USE [TestHekaton]
--ADD FILEGROUP 增加文件组
--ALTER DATABASE TestHekaton ADD FILEGROUP [default]
ALTER DATABASE TestHekaton ADD FILEGROUP [Report]
ALTER DATABASE TestHekaton ADD FILEGROUP [ASN]
ALTER DATABASE TestHekaton ADD FILEGROUP [Schedule]
ALTER DATABASE TestHekaton ADD FILEGROUP [PO]
ALTER DATABASE TestHekaton ADD FILEGROUP [Int]
ALTER DATABASE TestHekaton ADD FILEGROUP [His]
--内存文件组
ALTER DATABASE TestHekaton ADD FILEGROUP [MemoryFG] CONTAINS MEMORY_OPTIMIZED_DATA;